[tool.poetry]
name = "website-cv"
version = "0.1.0"
description = ""
authors = ["Fabrizio Giugno <fagi@hms-networks.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
lektor = "^3.3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
